// module.exports = {
//   StatusCodes: require("./statusCodes"),
//   ReasonPhrases: require("./reasonPhrases"),
// };

// httpStatusCode.ts

import * as StatusCodes from "./statusCodes";
import * as ReasonPhrases from "./reasonPhrases";

const httpStatusCode = {
  StatusCodes: {
    OK: StatusCodes.default.OK,
    CREATED: StatusCodes.default.CREATED,
    ACCEPTED: StatusCodes.default.ACCEPTED,
    NON_AUTHORITATIVE_INFORMATION:
      StatusCodes.default.NON_AUTHORITATIVE_INFORMATION,
    CONTINUE: StatusCodes.default.CONTINUE,
    SWITCHING_PROTOCOLS: StatusCodes.default.SWITCHING_PROTOCOLS,
    PROCESSING: StatusCodes.default.PROCESSING,
    NO_CONTENT: StatusCodes.default.NO_CONTENT,
    RESET_CONTENT: StatusCodes.default.RESET_CONTENT,
    PARTIAL_CONTENT: StatusCodes.default.PARTIAL_CONTENT,
    MULTI_STATUS: StatusCodes.default.MULTI_STATUS,
    ALREADY_REPORTED: StatusCodes.default.ALREADY_REPORTED,
    IM_USED: StatusCodes.default.IM_USED,
    MULTIPLE_CHOICES: StatusCodes.default.MULTIPLE_CHOICES,
    MOVED_PERMANENTLY: StatusCodes.default.MOVED_PERMANENTLY,
    FOUND: StatusCodes.default.FOUND,
    SEE_OTHER: StatusCodes.default.SEE_OTHER,
    NOT_MODIFIED: StatusCodes.default.NOT_MODIFIED,
    USE_PROXY: StatusCodes.default.USE_PROXY,
    TEMPORARY_REDIRECT: StatusCodes.default.TEMPORARY_REDIRECT,
    PERMANENT_REDIRECT: StatusCodes.default.PERMANENT_REDIRECT,
    BAD_REQUEST: StatusCodes.default.BAD_REQUEST,
    UNAUTHORIZED: StatusCodes.default.UNAUTHORIZED,
    PAYMENT_REQUIRED: StatusCodes.default.PAYMENT_REQUIRED,
    FORBIDDEN: StatusCodes.default.FORBIDDEN,
    NOT_FOUND: StatusCodes.default.NOT_FOUND,
    METHOD_NOT_ALLOWED: StatusCodes.default.METHOD_NOT_ALLOWED,
    NOT_ACCEPTABLE: StatusCodes.default.NOT_ACCEPTABLE,
    PROXY_AUTHENTICATION_REQUIRED:
      StatusCodes.default.PROXY_AUTHENTICATION_REQUIRED,
    REQUEST_TIMEOUT: StatusCodes.default.REQUEST_TIMEOUT,
    CONFLICT: StatusCodes.default.CONFLICT,
    GONE: StatusCodes.default.GONE,
    LENGTH_REQUIRED: StatusCodes.default.LENGTH_REQUIRED,
    PRECONDITION_FAILED: StatusCodes.default.PRECONDITION_FAILED,
    UNSUPPORTED_MEDIA_TYPE: StatusCodes.default.UNSUPPORTED_MEDIA_TYPE,
    EXPECTATION_FAILED: StatusCodes.default.EXPECTATION_FAILED,
    UNPROCESSABLE_ENTITY: StatusCodes.default.UNPROCESSABLE_ENTITY,
    LOCKED: StatusCodes.default.LOCKED,
    FAILED_DEPENDENCY: StatusCodes.default.FAILED_DEPENDENCY,
    UPGRADE_REQUIRED: StatusCodes.default.UPGRADE_REQUIRED,
    PRECONDITION_REQUIRED: StatusCodes.default.PRECONDITION_REQUIRED,
    TOO_MANY_REQUESTS: StatusCodes.default.TOO_MANY_REQUESTS,
    REQUEST_HEADER_FIELDS_TOO_LARGE:
      StatusCodes.default.REQUEST_HEADER_FIELDS_TOO_LARGE,
    INTERNAL_SERVER_ERROR: StatusCodes.default.INTERNAL_SERVER_ERROR,
    NOT_IMPLEMENTED: StatusCodes.default.NOT_IMPLEMENTED,
    BAD_GATEWAY: StatusCodes.default.BAD_GATEWAY,
    SERVICE_UNAVAILABLE: StatusCodes.default.SERVICE_UNAVAILABLE,
    GATEWAY_TIMEOUT: StatusCodes.default.GATEWAY_TIMEOUT,
    HTTP_VERSION_NOT_SUPPORTED: StatusCodes.default.HTTP_VERSION_NOT_SUPPORTED,
    VARIANT_ALSO_NEGOTIATES: StatusCodes.default.VARIANT_ALSO_NEGOTIATES,
    INSUFFICIENT_STORAGE: StatusCodes.default.INSUFFICIENT_STORAGE,
    LOOP_DETECTED: StatusCodes.default.LOOP_DETECTED,
    NOT_EXTENDED: StatusCodes.default.NOT_EXTENDED,
    NETWORK_AUTHENTICATION_REQUIRED:
      StatusCodes.default.NETWORK_AUTHENTICATION_REQUIRED,
  },
  ReasonPhrases: {
    OK: ReasonPhrases.default.OK,
    CREATED: ReasonPhrases.default.CREATED,
    ACCEPTED: ReasonPhrases.default.ACCEPTED,
    NON_AUTHORITATIVE_INFORMATION:
      ReasonPhrases.default.NON_AUTHORITATIVE_INFORMATION,
    CONTINUE: ReasonPhrases.default.CONTINUE,
    SWITCHING_PROTOCOLS: ReasonPhrases.default.SWITCHING_PROTOCOLS,
    PROCESSING: ReasonPhrases.default.PROCESSING,
    NO_CONTENT: ReasonPhrases.default.NO_CONTENT,
    RESET_CONTENT: ReasonPhrases.default.RESET_CONTENT,
    PARTIAL_CONTENT: ReasonPhrases.default.PARTIAL_CONTENT,
    MULTI_STATUS: ReasonPhrases.default.MULTI_STATUS,
    ALREADY_REPORTED: ReasonPhrases.default.ALREADY_REPORTED,
    IM_USED: ReasonPhrases.default.IM_USED,
    MULTIPLE_CHOICES: ReasonPhrases.default.MULTIPLE_CHOICES,
    MOVED_PERMANENTLY: ReasonPhrases.default.MOVED_PERMANENTLY,
    FOUND: ReasonPhrases.default.FOUND,
    SEE_OTHER: ReasonPhrases.default.SEE_OTHER,
    NOT_MODIFIED: ReasonPhrases.default.NOT_MODIFIED,
    USE_PROXY: ReasonPhrases.default.USE_PROXY,
    TEMPORARY_REDIRECT: ReasonPhrases.default.TEMPORARY_REDIRECT,
    PERMANENT_REDIRECT: ReasonPhrases.default.PERMANENT_REDIRECT,
    BAD_REQUEST: ReasonPhrases.default.BAD_REQUEST,
    UNAUTHORIZED: ReasonPhrases.default.UNAUTHORIZED,
    PAYMENT_REQUIRED: ReasonPhrases.default.PAYMENT_REQUIRED,
    FORBIDDEN: ReasonPhrases.default.FORBIDDEN,
    NOT_FOUND: ReasonPhrases.default.NOT_FOUND,
    METHOD_NOT_ALLOWED: ReasonPhrases.default.METHOD_NOT_ALLOWED,
    NOT_ACCEPTABLE: ReasonPhrases.default.NOT_ACCEPTABLE,
    PROXY_AUTHENTICATION_REQUIRED:
      ReasonPhrases.default.PROXY_AUTHENTICATION_REQUIRED,
    REQUEST_TIMEOUT: ReasonPhrases.default.REQUEST_TIMEOUT,
    CONFLICT: ReasonPhrases.default.CONFLICT,
    GONE: ReasonPhrases.default.GONE,
    LENGTH_REQUIRED: ReasonPhrases.default.LENGTH_REQUIRED,
    PRECONDITION_FAILED: ReasonPhrases.default.PRECONDITION_FAILED,
    UNSUPPORTED_MEDIA_TYPE: ReasonPhrases.default.UNSUPPORTED_MEDIA_TYPE,
    EXPECTATION_FAILED: ReasonPhrases.default.EXPECTATION_FAILED,
    UNPROCESSABLE_ENTITY: ReasonPhrases.default.UNPROCESSABLE_ENTITY,
    LOCKED: ReasonPhrases.default.LOCKED,
    FAILED_DEPENDENCY: ReasonPhrases.default.FAILED_DEPENDENCY,
    UPGRADE_REQUIRED: ReasonPhrases.default.UPGRADE_REQUIRED,
    PRECONDITION_REQUIRED: ReasonPhrases.default.PRECONDITION_REQUIRED,
    TOO_MANY_REQUESTS: ReasonPhrases.default.TOO_MANY_REQUESTS,
    REQUEST_HEADER_FIELDS_TOO_LARGE:
      ReasonPhrases.default.REQUEST_HEADER_FIELDS_TOO_LARGE,
    INTERNAL_SERVER_ERROR: ReasonPhrases.default.INTERNAL_SERVER_ERROR,
    NOT_IMPLEMENTED: ReasonPhrases.default.NOT_IMPLEMENTED,
    BAD_GATEWAY: ReasonPhrases.default.BAD_GATEWAY,
    SERVICE_UNAVAILABLE: ReasonPhrases.default.SERVICE_UNAVAILABLE,
    GATEWAY_TIMEOUT: ReasonPhrases.default.GATEWAY_TIMEOUT,
    HTTP_VERSION_NOT_SUPPORTED:
      ReasonPhrases.default.HTTP_VERSION_NOT_SUPPORTED,
    VARIANT_ALSO_NEGOTIATES: ReasonPhrases.default.VARIANT_ALSO_NEGOTIATES,
    INSUFFICIENT_STORAGE: ReasonPhrases.default.INSUFFICIENT_STORAGE,
    LOOP_DETECTED: ReasonPhrases.default.LOOP_DETECTED,
    NOT_EXTENDED: ReasonPhrases.default.NOT_EXTENDED,
    NETWORK_AUTHENTICATION_REQUIRED:
      ReasonPhrases.default.NETWORK_AUTHENTICATION_REQUIRED,
  },
};

export default httpStatusCode;
